### ISSUE TITLE
The ASM instrumenter is throwing a LinkageError when running on the h2bmark test benchmark.

### ISSUE THREAD

**Issue by greatmazinger** [ElephantTracksProject/et2-java#16]
The instrumenter runs for a bit then throws a LinkageError related to a class used by H2:

```
java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/h2/value/Value"
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

**Comment by greatmazinger** [comment]
A different stack trace of the same exception:

```
java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/h2/value/Value"                                          
    at java.lang.ClassLoader.defineClass1(Native Method)                                                                                                                                      
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)                                                                                                                                
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)                                                                                                                
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)                                                                                                                           
    at java.net.URLClassLoader.access$100(URLClassLoader.java:74)                                                                                                                             
    at java.net.URLClassLoader$1.run(URLClassLoader.java:369)                                                                                                                                 
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)                                                                                                                                 
    at java.security.AccessController.doPrivileged(Native Method)                                                                                                                             
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)                                                                                                                             
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)                                                                                                                                  
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)                                                                                                                          
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)                                                                                                                                  
    at org.h2.Driver.connect(Driver.java:69)                                                                                                                                                  
    at java.sql.DriverManager.getConnection(DriverManager.java:664)                                                                                                                           
    at java.sql.DriverManager.getConnection(DriverManager.java:270)                                                                                                                           
    at net.veroy.research.H2Bmark.main(H2Bmark.java:35
```

**Comment by greatmazinger** [comment]
I'm a little suspicious of the `sun/misc/Launcher$AppClassLoader`. At this point, I'm going to leave the H2 benchmark program aside for now, and work on getting the instumenter running on other benchmarks.

**Comment by xuanruiqi** [comment]
In practice, I think some of the benchmarks use Java in rather unusual ways (weird reflection, custom class loader, etc.) that are maybe not worth handling at this stage.

**Comment by greatmazinger** [comment]
Stopped using this benchmark for now since I have h2 running with the Javassist version of ET2.
May revisit this in the future.
