### ISSUE TITLE
Running ET2 (javassist) on DaCapo lusearch CannotCompileException

### ISSUE THREAD

**Issue by greatmazinger** [ElephantTracksProject/et2-java#18]
CannotCompile exceptions thrown, but lusearch manages to complete:

```
Error compiling new code into class/method:                                                                                                                                                   
Error compiling new code into class/method:                                                                                                                                                   
Error compiling new code into class/method:                                                                                                                                                   
javassist.CannotCompileException: by javassist.bytecode.BadBytecode: equals (Ljava/lang/Object;)Z in java.lang.Object: inconsistent stack height -1                                           
    at javassist.CtBehavior.insertAfter(CtBehavior.java:912)                                                                                                                                  
    at javassist.CtBehavior.insertAfter(CtBehavior.java:824)                                                                                                                                  
    at veroy.research.et2.javassist.MethodInstrumenter.instrumentMethods(MethodInstrumenter.java:68)                                                                                          
    at veroy.research.et2.javassist.Et2Transformer.transform(DynamicInstrumenter.java:80)                                                                                                     
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)                                                                                                               
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)                                                                                                             
    at sun.misc.Unsafe.defineClass(Native Method)                                                                                                                                             
    at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)                                                                                                                             
    at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)                                                                                                            
    at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)                                                                                                            
    at java.security.AccessController.doPrivileged(Native Method)                                                                                                                             
    at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)                                                                                                         
    at sun.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)                                                                                               
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)                                                                                           
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                                                   
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)                                                                                                                        
    at java.lang.Class.newInstance(Class.java:442)                                                                                                                                            
    at org.apache.lucene.index.SegmentReader.get(SegmentReader.java:301)                                                                                                                      
    at org.apache.lucene.index.SegmentReader.get(SegmentReader.java:269)                                                                                                                      
    at org.apache.lucene.index.DirectoryIndexReader$1.doBody(DirectoryIndexReader.java:100)                                                                                                   
    at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:653)                                                                                                       
    at org.apache.lucene.index.DirectoryIndexReader.open(DirectoryIndexReader.java:115)                                                                                                       
    at org.apache.lucene.index.IndexReader.open(IndexReader.java:316)                                                                                                                         
    at org.apache.lucene.index.IndexReader.open(IndexReader.java:206)                                                                                                                         
    at org.dacapo.lusearch.Search$QueryProcessor.<init>(Search.java:207)                                                                                                                      
    at org.dacapo.lusearch.Search$QueryThread.run(Search.java:179)                                                                                                                            
Caused by: javassist.bytecode.BadBytecode: equals (Ljava/lang/Object;)Z in java.lang.Object: inconsistent stack height -1                                                                     
    at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:119)                                                                                                                           
    at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:458)                                                                                                                     
    at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:440)                                                                                                                  
    at javassist.CtBehavior.insertAfter(CtBehavior.java:903)                                                                                                                                  
    ... 25 more 
```

**Comment by greatmazinger** [comment]
This is looking like a concurrency issue. I set the thread count to 1 and it successfully finishes.

**Comment by greatmazinger** [comment]
Passes with thread count = 1:
```
Loading Agent..
Using scaled threading model. 64 processors detected, 1 threads used to drive the workload, in a possible range of [1,64]
===== DaCapo 9.12 lusearch starting =====
a^H4 query batches completed
8 query batches completed
12 query batches completed
16 query batches completed
20 query batches completed
24 query batches completed
28 query batches completed
32 query batches completed
36 query batches completed
40 query batches completed
44 query batches completed
48 query batches completed
52 query batches completed
56 query batches completed
60 query batches completed
64 query batches completed
===== DaCapo 9.12 lusearch PASSED in 2942994 msec =====
```

**Comment by greatmazinger** [comment]
Passes with thread count = 2:
```
Loading Agent..
Using scaled threading model. 64 processors detected, 2 threads used to drive the workload, in a possible range of [1,64]
===== DaCapo 9.12 lusearch starting =====
4 query batches completed
8 query batches completed
12 query batches completed
16 query batches completed
20 query batches completed
24 query batches completed
28 query batches completed
32 query batches completed
36 query batches completed
40 query batches completed
44 query batches completed
48 query batches completed
52 query batches completed
56 query batches completed
60 query batches completed
64 query batches completed
===== DaCapo 9.12 lusearch PASSED in 3299596 msec =====
```

While this ultimately is not proof that it is race free at thread == 2, it's still good to see it pass. :)

**Comment by greatmazinger** [comment]
Passes with thread count = 4:
```
Loading Agent..
Using scaled threading model. 64 processors detected, 4 threads used to drive the workload, in a possible range of [1,64]
===== DaCapo 9.12 lusearch starting =====
4 query batches completed
8 query batches completed
12 query batches completed
16 query batches completed
20 query batches completed
24 query batches completed
28 query batches completed
32 query batches completed
36 query batches completed
40 query batches completed
44 query batches completed
48 query batches completed
52 query batches completed
56 query batches completed
60 query batches completed
64 query batches completed
===== DaCapo 9.12 lusearch PASSED in 3135449 msec =====
```

**Comment by greatmazinger** [comment]
Passed all the way to 32. Maybe it's fixed now? :)

**Comment by greatmazinger** [comment]
Works all the way up to 56 threads. For some reason, things mess up at 64. Clearly it's not perfect, but not sure what is wrong. Closing this for now.

**Comment by xuanruiqi** [comment]
Very weird error here.
